const assert=require('node:assert/strict'),{api:a}=require('./simcore');
const tower=a.ACTS.findIndex(x=>x.id==='tower');let count=0;
function test(name,fn){fn();count++;console.log('PASS '+name);}
function start(seed=81291){a.VILLAGE().act=tower;a.VILLAGE().condition=null;a.newGame(seed);a.G().mons=[];return a.G();}
test('first terrace always has a discovery; outcomes are stable and do not consume turns',()=>{for(let seed=1;seed<=30;seed++){const g=start(seed),turn=g.turn,state={...a.terraceState()};assert.notEqual(state.event,'quiet');assert.deepEqual(a.terraceState(),state);assert.equal(g.turn,turn);start(seed);assert.deepEqual(a.terraceState(),state);}});
test('rest is limited, never wasted at full health, and preserves hunger and pressure',()=>{const g=start();g.f.elapsedTurns=600;g.p.hp=g.p.mhp;g.p.mp=g.p.mmp;assert.equal(a.terraceRest().code,'full');assert(!a.terraceState().rested);g.p.hp=1;g.p.mp=0;const hp=g.p.mhp,mp=g.p.mmp,sat=g.p.sat,turn=g.turn;assert(a.terraceRest().ok);assert.equal(g.p.hp,1+Math.ceil(hp*.35));assert.equal(g.p.mp,Math.ceil(mp*.25));assert.equal(a.terraceRest().code,'used');assert.equal(g.p.sat,sat);assert.equal(g.f.elapsedTurns,600);assert.equal(g.turn,turn);});
test('claim is atomic when bag is full and cannot be repeated',()=>{const g=start(),s=a.terraceState();g.p.inv=Array.from({length:20},()=>a.mk('food','bread'));assert.equal(a.terraceClaim().code,'bag');assert(!s.claimed);g.p.inv.pop();assert(a.terraceClaim().ok);assert.equal(g.p.inv.length,20);assert.equal(a.terraceClaim().code,'empty');});
test('save and reload preserve discoveries, spent recovery and granted item exactly once',()=>{const g=start();g.p.hp=1;a.terraceRest();const item=a.terraceClaim().item;const expected={...a.terraceState()},n=g.p.inv.filter(i=>i.id===item.id).length;a.saveRun();const q=a.loadedRun();a.resumeRun(q);assert.deepEqual(a.terraceState(),expected);assert.equal(a.terraceRest().code,'used');assert.equal(a.terraceClaim().code,'empty');assert.equal(a.G().p.inv.filter(i=>i.id===item.id).length,n);});
test('old saves remain compatible and different floors retain separate state',()=>{const g=start();a.terraceState().claimed=true;g.floor=2;const two=a.terraceState();assert(!two.claimed);g.floor=1;assert(a.terraceState().claimed);a.restoreTerraces(undefined);assert(!a.terraceState().claimed);a.restoreTerraces({'bad':{},'14:1':null});assert(!a.terraceState().claimed);});
test('later floors include quiet moments and multiple encounter types',()=>{const outcomes=new Set();for(let seed=1;seed<=100;seed++){const g=start(seed);g.floor=2;outcomes.add(a.terraceState().event);}assert.deepEqual([...outcomes].sort(),['cache','light','quiet','traveler']);});
console.log('Terrace: '+count+' checks passed.');
